languageCode = "en-us"
title = "DV Golden Time Shipping and Insurance"
baseurl = "https://dvgolden.github.io/"
theme = "minimal"
MedaDataFormat = "toml"

[params]
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

#contact setion
[params.contact]
    buttonText = "Send message"
# 'warning' defines error messages for invalid inputs
[params.contact.form.name]
  text = "Your Name *"
  warning = "Please enter your name."

[params.contact.form.email]
  text = "Your Email *"
  warning = "Please enter your email address."

[params.contact.form.phone]
  text = "Your Phone *"
  warning = "Please enter your phone number."

[params.contact.form.message]
  text = "Your Message *"
  warning = "Please enter a message."
