# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "BcBasic"
author = "Dan Burgett"
description = "A basic theme for bugett consulting clients"
homepage = "https://burgettconsulting.com/"
min_version = 0.18
